### ISSUE TITLE
Wrong KeyState

### ISSUE THREAD

**Issue by UltraV10lence** [arcanexhoax/GlobalKeyInterceptor#2]
In KeyInterceptor.OnKeyPressed keyStete is totally ignored and not passed in Shortcut constructor.

**Comment by UltraV10lence** [comment]
Of course!
```C#
var interceptor = new KeyInterceptor();
interceptor.ShortcutPressed += (_, e) => {
    Console.WriteLine($"State of key {e.Shortcut.Key}: {e.Shortcut.State}");
};

interceptor.RunMessageLoop();
```

After I've pressed a few keys, the output should be something like this:
```
State of key A: Down
State of key A: Up
State of key S: Down
State of key S: Up
State of key D: Down
State of key D: Up
```

But in practice, it looks like this:
```
State of key A: Up
State of key A: Up
State of key S: Up
State of key S: Up
State of key D: Up
State of key D: Up
```

Are there any other questions about the problem?

**Comment by arcanexhoax** [comment]
Got it! I'll fix it soon

**Comment by arcanexhoax** [comment]
Here is [v1.2.1](https://github.com/arcanexhoax/GlobalKeyInterceptor/releases/tag/v1.2.1)
